spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/giftcard
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    
server:
  port: 8081